require 'yaml'
def carousel()
    data =  YAML.load_file('site/data/ad.yaml')
    time = File.readlines('site/data/ad.yaml').length
    # Generates uniqe ID´s that can be assigned to items.
    #  TODO: make this variable dynamic based on number of "ads"
    # It is currently semi dynamic
    time = time/5
    
    stored = []
    value = []
    while stored.length < time
        8.times{ value  << (97 + rand(25)).chr }
        temp = value.join()
        if stored.include?(temp) == false
            stored << temp
        end
        value = [] 
    end
    puts 'Autogenerated ID´s:'
    puts stored

    mobile = ""
    desktop = ""
    tablet = ""
    output = []
    id = 0
    i = 0
    data['mainad'].each do |variable|
        img = variable['mobile']     
        id += 1
        input = stored[id-1] + ' = document.getElementById("img' + id.to_s + '");' + stored[id-1] + '.style.backgroundImage = "url(img/' + img + ')";'
        mobile += stored[id-1] + '.style.backgroundImage = "url(img/' + variable['mobile'] + ')";'
        tablet += stored[id-1] + '.style.backgroundImage = "url(img/' + variable['tablet'] + ')";'
        desktop += stored[id-1] + '.style.backgroundImage = "url(img/' + variable['desktop'] + ')";'
        i += 1
        output << input
    end

    i = 0
    data['popularad'].each do |variable|
        img = variable['mobile']     
        id += 1
        input = stored[id-1] + ' = document.getElementById("img' + id.to_s + '");' + stored[id-1] + '.style.backgroundImage = "url(img/' + img + ')";'
        mobile += stored[id-1] + '.style.backgroundImage = "url(img/' + variable['mobile'] + ')";'
        tablet += stored[id-1] + '.style.backgroundImage = "url(img/' + variable['tablet'] + ')";'
        desktop += stored[id-1] + '.style.backgroundImage = "url(img/' + variable['desktop'] + ')";'
        i += 1
        output << input
    end

    i = 0
    data['smartdevices'].each do |variable|
        img = variable['mobile']     
        id += 1
        input = stored[id-1] + ' = document.getElementById("img' + id.to_s + '");' + stored[id-1] + '.style.backgroundImage = "url(img/' + img + ')";'
        mobile += stored[id-1] + '.style.backgroundImage = "url(img/' + variable['mobile'] + ')";'
        tablet += stored[id-1] + '.style.backgroundImage = "url(img/' + variable['tablet'] + ')";'
        desktop += stored[id-1] + '.style.backgroundImage = "url(img/' + variable['desktop'] + ')";'
        i += 1
        output << input
    end
    
    temp_media = 'function mediaQuery(y, z) { if (z.matches) {' + mobile + '} else if (y.matches) {' + tablet + '} else {' + desktop + '}}var y = window.matchMedia("(max-width: 1024px)");var z = window.matchMedia("(max-width: 480px)");mediaQuery(y, z); (function() {var throttle = function(type, name, obj) {obj = obj || window;var running = false;var func = function() {if (running) { return; }running = true;requestAnimationFrame(function() {obj.dispatchEvent(new CustomEvent(name));running = false; });}; obj.addEventListener(type, func); }; throttle("resize", "optimizedResize"); })(); window.addEventListener("optimizedResize", function() { mediaQuery(y,z); });'
    
    
    
    temp = ""
    output.each do |variable|
        temp += variable
    end
    write = temp + temp_media
    
    File.write('site/js/ad.js', write)
    print "\nCompleted tasks:\nad.js created \n"
end